### ISSUE TITLE
Nombre de archivos

### ISSUE THREAD

**Issue by nmicht** [HawkRS/Terrasse#2]
- [ ] Los archivos por estándar (al menos los html) deberían estar en minúsculas
- [ ] Por estándar en web los archivos no llevan espacios
- [ ] Estandarizar nombres en español o inglés pero no mezclar

![seleccion_293](https://cloud.githubusercontent.com/assets/1750293/18748991/7397667c-809a-11e6-9723-8d287705b2fd.png)

**Comment by HawkRS** [comment]
Solucionado
